// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgres

import (
	"database/sql"
)

type User struct {
	ID          int32          `json:"id"`
	Name        sql.NullString `json:"name"`
	PhoneNumber string         `json:"phone_number"`
}

type UsersOtp struct {
	PhoneNumberOtp    string         `json:"phone_number_otp"`
	Otp               sql.NullString `json:"otp"`
	OtpExpirationTime sql.NullTime   `json:"otp_expiration_time"`
}
